### ISSUE TITLE
Consider updating the list to follow Awesome guidelines

### ISSUE THREAD

**Issue by mcanouil** [nanxstats/awesome-webr#2]
See <https://github.com/sindresorhus/awesome/blob/main/awesome.md> and <https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-awesome-list>.

Currently, the list does not follow most of the guidelines to be considered as an "Awesome list" as defined in <https://github.com/sindresorhus/awesome> which is suggested by the fact the badge is in the readme.

**Comment by nanxstats** [comment]
Nice - I would surely welcome a PR in case anything should be updated following the guidelines.

**Comment by nanxstats** [comment]
(See suggestions from https://github.com/nanxstats/awesome-webr/pull/1 on submitting to the main list)

**Comment by nanxstats** [comment]
OK, since now all checks are passing, I will close this. Thanks again for all the great suggestions and PRs!

The check list for submitting to the main awesome list seems super long... I'm not ready to spend time on it. Perhaps will revisit that at another time.
