### ISSUE TITLE
Awesome Bot setup

### ISSUE THREAD

**Issue by mcanouil** [nanxstats/awesome-webr#4]
You might want to allow some error in URI checks as well as to add URIs to whitelist.
See <https://github.com/dkhamsing/awesome_bot> for more control on URI checks.

**Comment by nanxstats** [comment]
Sure, I will take a look.

**Comment by nanxstats** [comment]
Fixed by https://github.com/nanxstats/awesome-webr/commit/5befc12f3e015d465822b725e7a94b677ecaf88d and https://github.com/nanxstats/awesome-webr/commit/1d3360c76456471918ef0c3f8829432361a18cd5.
